version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_APP_BACKEND_URL: https://638f-102-109-111-249.ngrok-free.app
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Ab@14615751
      DB_NAME: CoCal

      JWT_KEY: 72eac1861442b85ba4d01372bf6a965a365ea850c8ef3966b2f494d0d4e833c1
      EMAIL_USER: abdallahjbeli55@gmail.com
      EMAIL_PASSWORD: uipditgxahvkfypo
      FRONTEND_URL: http://frontend:5173/
      PORT: 5000 #
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ab@14615751
      MYSQL_DATABASE: CoCal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pAb@14615751",
        ]
      timeout: 20s
      retries: 10
      interval: 5s
    restart: unless-stopped

volumes:
  db_data:
