version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_APP_BACKEND_URL: https://34a9-197-2-37-28.ngrok-free.app
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Database connection variables (these override your backend/.env)
      DB_HOST: db # This matches the service name of your database container
      DB_USER: root
      DB_PASSWORD: Ab@14615751
      DB_NAME: CoCal # As per your .env

      # Other backend environment variables from your .env
      JWT_KEY: 72eac1861442b85ba4d01372bf6a965a365ea850c8ef3966b2f494d0d4e833c1
      EMAIL_USER: abdallahjbeli55@gmail.com
      EMAIL_PASSWORD: uipditgxahvkfypo # <<<<<< Consider using Docker secrets for sensitive info in production
      FRONTEND_URL: http://frontend:5173/ # Use the Docker service name for frontend
      PORT: 5000 # Though often implicitly handled by Node.js apps
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ab@14615751 # <<<<<< MUST MATCH DB_PASSWORD IN BACKEND SERVICE!
      MYSQL_DATABASE: CoCal # <<<<<< MUST MATCH DB_NAME IN BACKEND SERVICE!
    ports:
      - "3306:3306" # Optional for external access, keep for now if you need it
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pAb@14615751",
        ]
      timeout: 20s
      retries: 10
      interval: 5s
    restart: unless-stopped

volumes:
  db_data:
